// <auto-generated />
namespace NCKH.HTMLSteg.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addNAmeHTML : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addNAmeHTML));
        
        string IMigrationMetadata.Id
        {
            get { return "202007061646221_addNAmeHTML"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
